### ISSUE TITLE
auto-deploy no work

### ISSUE THREAD

**Issue by rxa254** [rxa254/StatisticalPhysics#1]
how to make the compiled latex show up?

**Comment by rxa254** [comment]
@jwrichardson I got the Latex to compile, but I get 'missing token' on the travis log. Some help on how to make the compiled PDF link show up somewhere?

**Comment by jwrichardson** [comment]
I fixed it. There were two problems: (1) You set Travis to authenticate via a Github access token, but didn't actually provide it in the .travis.yml config file. I generated one following step 2.2 of these [instructions](https://gist.github.com/anchal-physics/c219a617293e9098b726bcb33692825f). (2) The link to the autogenerated PDF in the readme was wrong (was pointed to the root directory instead of the LectureNotes subdirectory).

**Comment by jwrichardson** [comment]
@rxa254 Also, not directly related since this repo is not under CaltechExperimentalGravity, but it looks like Travis CI is disabled for all the repos in this group:

"Builds have been temporarily disabled for private repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance."

**Comment by rxa254** [comment]
thanks! how did you see that error message about the billing?

**Comment by rxa254** [comment]
founh that the big usage was in the Docker building in our openai/gym fork. Turned off now.

**Comment by jwrichardson** [comment]
That billing message was in an announcement banner when I logged into travis-ci.com. Recent commits from CaltechExperimentalGravity repos also showed up in the job history as not executed.
